#!/bin/bash
make -f Makefile.rpi clean
make -f Makefile.rpi OPTS="-DLINKALL -DDSD -DVISEXPORT -DRESAMPLE -DIR -DGPIO -DRPI -I./include" LDFLAGS="/usr/lib/arm-linux-gnueabihf/libFLAC.a /usr/lib/arm-linux-gnueabihf/libvorbisfile.a /usr/lib/arm-linux-gnueabihf/libvorbis.a /usr/lib/arm-linux-gnueabihf/libogg.a /usr/lib/arm-linux-gnueabihf/libmad.a /usr/lib/arm-linux-gnueabihf/libfaad.a /usr/lib/arm-linux-gnueabihf/libmpg123.so /usr/lib/arm-linux-gnueabihf/libsoxr.so /usr/lib/arm-linux-gnueabihf/liblirc_client.so /usr/lib/gcc/arm-linux-gnueabihf/6/libgomp.a /usr/lib/libwiringPi.so -lpthread -ldl -lrt -lm -lasound"

strip squeezelite-rpi
mv squeezelite-rpi squeezelite-armv6hf-noffmpeg

make -f Makefile.rpi clean
make -f Makefile.rpi OPTS="-DLINKALL -DFFMPEG -DDSD -DVISEXPORT -DRESAMPLE -DIR -DGPIO -DRPI -I./include" LDFLAGS="/usr/lib/arm-linux-gnueabihf/libFLAC.a /usr/lib/arm-linux-gnueabihf/libvorbisfile.a /usr/lib/arm-linux-gnueabihf/libvorbis.a /usr/lib/arm-linux-gnueabihf/libogg.a /usr/lib/arm-linux-gnueabihf/libmad.a /usr/lib/arm-linux-gnueabihf/libfaad.a /usr/lib/arm-linux-gnueabihf/libmpg123.so /usr/lib/arm-linux-gnueabihf/libswscale.a /usr/lib/arm-linux-gnueabihf/libavdevice.a /usr/lib/arm-linux-gnueabihf/libavformat.a /usr/lib/arm-linux-gnueabihf/libavcodec.a /usr/lib/arm-linux-gnueabihf/libswresample.a /usr/lib/arm-linux-gnueabihf/libavutil.a /usr/lib/arm-linux-gnueabihf/libsoxr.so /usr/lib/gcc/arm-linux-gnueabihf/6/libgomp.a /usr/lib/arm-linux-gnueabihf/liblirc_client.so /usr/lib/libwiringPi.so -lpthread -ldl -lrt -lm -lasound"

strip squeezelite-rpi
mv squeezelite-rpi squeezelite-armv6hf-ffmpeg

